language: python
python:
- 3.8
before_install:
- pip install poetry
install:
- poetry install
script:
- cd python
- poetry run python -m pytest tests
- poetry run mypy *.py --ignore-missing-imports
- poetry run python -m pytest --cov-report xml --cov=. tests/
- bash <(curl -s https://codecov.io/bash)
